# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testes de API

on:
  push:
  pull_request:

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Install and exec tests
        run: npm ci && npm run test:prod

      - name: Build and Deploy
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: report
