# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testes de API

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  teste-de-api-com-serverest:
    runs-on: ubuntu-18.04

   steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
    - name: Setup do Node.js
      uses: actions/setup-node@v2.1.1
    - name: Instalar as dependências do projeto
      run: npm ci
    - name: Executar os testes de API
      run: npm run test:prod
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: report
